//! RISC-V disassembler: renders a decoded [`Insn`] as GNU-style assembly with
//! ABI register names. Used for tracing and trap diagnostics.

use std::fmt;

use super::decode::{Insn, Op};
use super::{f_name, x_name};

impl Op {
    /// The assembler mnemonic for this operation.
    pub fn mnemonic(self) -> &'static str {
        use Op::*;
        match self {
            Lui => "lui",
            Auipc => "auipc",
            Jal => "jal",
            Jalr => "jalr",
            Beq => "beq",
            Bne => "bne",
            Blt => "blt",
            Bge => "bge",
            Bltu => "bltu",
            Bgeu => "bgeu",
            Lb => "lb",
            Lh => "lh",
            Lw => "lw",
            Lbu => "lbu",
            Lhu => "lhu",
            Lwu => "lwu",
            Ld => "ld",
            Sb => "sb",
            Sh => "sh",
            Sw => "sw",
            Sd => "sd",
            Addi => "addi",
            Slti => "slti",
            Sltiu => "sltiu",
            Xori => "xori",
            Ori => "ori",
            Andi => "andi",
            Slli => "slli",
            Srli => "srli",
            Srai => "srai",
            Add => "add",
            Sub => "sub",
            Sll => "sll",
            Slt => "slt",
            Sltu => "sltu",
            Xor => "xor",
            Srl => "srl",
            Sra => "sra",
            Or => "or",
            And => "and",
            Addiw => "addiw",
            Slliw => "slliw",
            Srliw => "srliw",
            Sraiw => "sraiw",
            Addw => "addw",
            Subw => "subw",
            Sllw => "sllw",
            Srlw => "srlw",
            Sraw => "sraw",
            Fence => "fence",
            FenceI => "fence.i",
            Ecall => "ecall",
            Ebreak => "ebreak",
            Mret => "mret",
            Sret => "sret",
            Wfi => "wfi",
            Csrrw => "csrrw",
            Csrrs => "csrrs",
            Csrrc => "csrrc",
            Csrrwi => "csrrwi",
            Csrrsi => "csrrsi",
            Csrrci => "csrrci",
            Mul => "mul",
            Mulh => "mulh",
            Mulhsu => "mulhsu",
            Mulhu => "mulhu",
            Div => "div",
            Divu => "divu",
            Rem => "rem",
            Remu => "remu",
            Mulw => "mulw",
            Divw => "divw",
            Divuw => "divuw",
            Remw => "remw",
            Remuw => "remuw",
            LrW => "lr.w",
            ScW => "sc.w",
            AmoswapW => "amoswap.w",
            AmoaddW => "amoadd.w",
            AmoxorW => "amoxor.w",
            AmoandW => "amoand.w",
            AmoorW => "amoor.w",
            AmominW => "amomin.w",
            AmomaxW => "amomax.w",
            AmominuW => "amominu.w",
            AmomaxuW => "amomaxu.w",
            LrD => "lr.d",
            ScD => "sc.d",
            AmoswapD => "amoswap.d",
            AmoaddD => "amoadd.d",
            AmoxorD => "amoxor.d",
            AmoandD => "amoand.d",
            AmoorD => "amoor.d",
            AmominD => "amomin.d",
            AmomaxD => "amomax.d",
            AmominuD => "amominu.d",
            AmomaxuD => "amomaxu.d",
            Flw => "flw",
            Fsw => "fsw",
            FmaddS => "fmadd.s",
            FmsubS => "fmsub.s",
            FnmsubS => "fnmsub.s",
            FnmaddS => "fnmadd.s",
            FaddS => "fadd.s",
            FsubS => "fsub.s",
            FmulS => "fmul.s",
            FdivS => "fdiv.s",
            FsqrtS => "fsqrt.s",
            FsgnjS => "fsgnj.s",
            FsgnjnS => "fsgnjn.s",
            FsgnjxS => "fsgnjx.s",
            FminS => "fmin.s",
            FmaxS => "fmax.s",
            FcvtWS => "fcvt.w.s",
            FcvtWuS => "fcvt.wu.s",
            FcvtLS => "fcvt.l.s",
            FcvtLuS => "fcvt.lu.s",
            FmvXW => "fmv.x.w",
            FeqS => "feq.s",
            FltS => "flt.s",
            FleS => "fle.s",
            FclassS => "fclass.s",
            FcvtSW => "fcvt.s.w",
            FcvtSWu => "fcvt.s.wu",
            FcvtSL => "fcvt.s.l",
            FcvtSLu => "fcvt.s.lu",
            FmvWX => "fmv.w.x",
            Fld => "fld",
            Fsd => "fsd",
            FmaddD => "fmadd.d",
            FmsubD => "fmsub.d",
            FnmsubD => "fnmsub.d",
            FnmaddD => "fnmadd.d",
            FaddD => "fadd.d",
            FsubD => "fsub.d",
            FmulD => "fmul.d",
            FdivD => "fdiv.d",
            FsqrtD => "fsqrt.d",
            FsgnjD => "fsgnj.d",
            FsgnjnD => "fsgnjn.d",
            FsgnjxD => "fsgnjx.d",
            FminD => "fmin.d",
            FmaxD => "fmax.d",
            FcvtSD => "fcvt.s.d",
            FcvtDS => "fcvt.d.s",
            FeqD => "feq.d",
            FltD => "flt.d",
            FleD => "fle.d",
            FclassD => "fclass.d",
            FcvtWD => "fcvt.w.d",
            FcvtWuD => "fcvt.wu.d",
            FcvtLD => "fcvt.l.d",
            FcvtLuD => "fcvt.lu.d",
            FcvtDW => "fcvt.d.w",
            FcvtDWu => "fcvt.d.wu",
            FcvtDL => "fcvt.d.l",
            FcvtDLu => "fcvt.d.lu",
            FmvXD => "fmv.x.d",
            FmvDX => "fmv.d.x",
            Sh1add => "sh1add",
            Sh2add => "sh2add",
            Sh3add => "sh3add",
            AddUw => "add.uw",
            Sh1addUw => "sh1add.uw",
            Sh2addUw => "sh2add.uw",
            Sh3addUw => "sh3add.uw",
            SlliUw => "slli.uw",
            Andn => "andn",
            Orn => "orn",
            Xnor => "xnor",
            Clz => "clz",
            Ctz => "ctz",
            Cpop => "cpop",
            Max => "max",
            Maxu => "maxu",
            Min => "min",
            Minu => "minu",
            SextB => "sext.b",
            SextH => "sext.h",
            ZextH => "zext.h",
            Rol => "rol",
            Ror => "ror",
            Rori => "rori",
            Orcb => "orc.b",
            Rev8 => "rev8",
            Clzw => "clzw",
            Ctzw => "ctzw",
            Cpopw => "cpopw",
            Rolw => "rolw",
            Rorw => "rorw",
            Roriw => "roriw",
            Clmul => "clmul",
            Clmulh => "clmulh",
            Clmulr => "clmulr",
            Bclr => "bclr",
            Bclri => "bclri",
            Bext => "bext",
            Bexti => "bexti",
            Binv => "binv",
            Binvi => "binvi",
            Bset => "bset",
            Bseti => "bseti",
            CzeroEqz => "czero.eqz",
            CzeroNez => "czero.nez",
            FliS => "fli.s",
            FliD => "fli.d",
            FminmS => "fminm.s",
            FmaxmS => "fmaxm.s",
            FminmD => "fminm.d",
            FmaxmD => "fmaxm.d",
            FroundS => "fround.s",
            FroundnxS => "froundnx.s",
            FroundD => "fround.d",
            FroundnxD => "froundnx.d",
            FleqS => "fleq.s",
            FltqS => "fltq.s",
            FleqD => "fleq.d",
            FltqD => "fltq.d",
            FcvtmodWD => "fcvtmod.w.d",
            Pack => "pack",
            Packh => "packh",
            Packw => "packw",
            Brev8 => "brev8",
            Flh => "flh",
            Fsh => "fsh",
            FaddH => "fadd.h",
            FsubH => "fsub.h",
            FmulH => "fmul.h",
            FdivH => "fdiv.h",
            FsqrtH => "fsqrt.h",
            FmaddH => "fmadd.h",
            FmsubH => "fmsub.h",
            FnmsubH => "fnmsub.h",
            FnmaddH => "fnmadd.h",
            FsgnjH => "fsgnj.h",
            FsgnjnH => "fsgnjn.h",
            FsgnjxH => "fsgnjx.h",
            FminH => "fmin.h",
            FmaxH => "fmax.h",
            FeqH => "feq.h",
            FltH => "flt.h",
            FleH => "fle.h",
            FclassH => "fclass.h",
            FcvtSH => "fcvt.s.h",
            FcvtHS => "fcvt.h.s",
            FcvtDH => "fcvt.d.h",
            FcvtHD => "fcvt.h.d",
            FcvtWH => "fcvt.w.h",
            FcvtWuH => "fcvt.wu.h",
            FcvtLH => "fcvt.l.h",
            FcvtLuH => "fcvt.lu.h",
            FcvtHW => "fcvt.h.w",
            FcvtHWu => "fcvt.h.wu",
            FcvtHL => "fcvt.h.l",
            FcvtHLu => "fcvt.h.lu",
            FmvXH => "fmv.x.h",
            FmvHX => "fmv.h.x",
            FliH => "fli.h",
            FminmH => "fminm.h",
            FmaxmH => "fmaxm.h",
            FroundH => "fround.h",
            FroundnxH => "froundnx.h",
            FleqH => "fleq.h",
            FltqH => "fltq.h",
            Xperm4 => "xperm4",
            Xperm8 => "xperm8",
            Sha256Sig0 => "sha256sig0",
            Sha256Sig1 => "sha256sig1",
            Sha256Sum0 => "sha256sum0",
            Sha256Sum1 => "sha256sum1",
            Sha512Sig0 => "sha512sig0",
            Sha512Sig1 => "sha512sig1",
            Sha512Sum0 => "sha512sum0",
            Sha512Sum1 => "sha512sum1",
            Sm3p0 => "sm3p0",
            Sm3p1 => "sm3p1",
            Sm4ed => "sm4ed",
            Sm4ks => "sm4ks",
            Aes64es => "aes64es",
            Aes64esm => "aes64esm",
            Aes64ds => "aes64ds",
            Aes64dsm => "aes64dsm",
            Aes64ks1i => "aes64ks1i",
            Aes64ks2 => "aes64ks2",
            Aes64im => "aes64im",
            Vsetvli => "vsetvli",
            Vsetivli => "vsetivli",
            Vsetvl => "vsetvl",
            Vle => "vle.v",
            Vse => "vse.v",
            Vadd => "vadd",
            Vsub => "vsub",
            Vrsub => "vrsub",
            Vand => "vand",
            Vor => "vor",
            Vxor => "vxor",
            Vminu => "vminu",
            Vmin => "vmin",
            Vmaxu => "vmaxu",
            Vmax => "vmax",
            Vsll => "vsll",
            Vsrl => "vsrl",
            Vsra => "vsra",
            Vmerge => "vmerge",
            Vmseq => "vmseq",
            Vmsne => "vmsne",
            Vmsltu => "vmsltu",
            Vmslt => "vmslt",
            Vmsleu => "vmsleu",
            Vmsle => "vmsle",
            Vmsgtu => "vmsgtu",
            Vmsgt => "vmsgt",
            Vmul => "vmul",
            Vmulh => "vmulh",
            Vmulhu => "vmulhu",
            Vmulhsu => "vmulhsu",
            Vdivu => "vdivu",
            Vdiv => "vdiv",
            Vremu => "vremu",
            Vrem => "vrem",
            Vlse => "vlse",
            Vsse => "vsse",
            Vlxei => "vlxei",
            Vsxei => "vsxei",
            Vlm => "vlm.v",
            Vsm => "vsm.v",
            Vlre => "vlre.v",
            Vsre => "vsre.v",
            Vlseg => "vlseg",
            Vsseg => "vsseg",
            Vleff => "vleff",
            Vfadd => "vfadd",
            Vfsub => "vfsub",
            Vfrsub => "vfrsub",
            Vfmul => "vfmul",
            Vfdiv => "vfdiv",
            Vfrdiv => "vfrdiv",
            Vfsqrt => "vfsqrt",
            Vfmin => "vfmin",
            Vfmax => "vfmax",
            Vfsgnj => "vfsgnj",
            Vfsgnjn => "vfsgnjn",
            Vfsgnjx => "vfsgnjx",
            Vmfeq => "vmfeq",
            Vmfne => "vmfne",
            Vmflt => "vmflt",
            Vmfle => "vmfle",
            Vmfgt => "vmfgt",
            Vmfge => "vmfge",
            Vfmacc => "vfmacc",
            Vfnmacc => "vfnmacc",
            Vfmsac => "vfmsac",
            Vfnmsac => "vfnmsac",
            Vfmadd => "vfmadd",
            Vfnmadd => "vfnmadd",
            Vfmsub => "vfmsub",
            Vfnmsub => "vfnmsub",
            Vredsum => "vredsum",
            Vredand => "vredand",
            Vredor => "vredor",
            Vredxor => "vredxor",
            Vredminu => "vredminu",
            Vredmin => "vredmin",
            Vredmaxu => "vredmaxu",
            Vredmax => "vredmax",
            Vfredusum => "vfredusum",
            Vfredosum => "vfredosum",
            Vfredmin => "vfredmin",
            Vfredmax => "vfredmax",
            VmvXS => "vmv.x.s",
            VmvSX => "vmv.s.x",
            VfmvFS => "vfmv.f.s",
            VfmvSF => "vfmv.s.f",
            Vmand => "vmand",
            Vmnand => "vmnand",
            Vmandn => "vmandn",
            Vmxor => "vmxor",
            Vmor => "vmor",
            Vmnor => "vmnor",
            Vmorn => "vmorn",
            Vmxnor => "vmxnor",
            VzextVf2 => "vzext.vf2",
            VsextVf2 => "vsext.vf2",
            VzextVf4 => "vzext.vf4",
            VsextVf4 => "vsext.vf4",
            VzextVf8 => "vzext.vf8",
            VsextVf8 => "vsext.vf8",
            Vcpop => "vcpop.m",
            Vfirst => "vfirst.m",
            Vmsbf => "vmsbf.m",
            Vmsof => "vmsof.m",
            Vmsif => "vmsif.m",
            Viota => "viota.m",
            Vid => "vid.v",
            Vslideup => "vslideup",
            Vslidedown => "vslidedown",
            Vslide1up => "vslide1up",
            Vslide1down => "vslide1down",
            Vfslide1up => "vfslide1up",
            Vfslide1down => "vfslide1down",
            Vrgather => "vrgather",
            Vrgatherei16 => "vrgatherei16",
            Vcompress => "vcompress",
            Vadc => "vadc",
            Vmadc => "vmadc",
            Vsbc => "vsbc",
            Vmsbc => "vmsbc",
            Vsaddu => "vsaddu",
            Vsadd => "vsadd",
            Vssubu => "vssubu",
            Vssub => "vssub",
            Vaaddu => "vaaddu",
            Vaadd => "vaadd",
            Vasubu => "vasubu",
            Vasub => "vasub",
            Vssrl => "vssrl",
            Vssra => "vssra",
            Vsmul => "vsmul",
            Vwaddu => "vwaddu",
            Vwadd => "vwadd",
            Vwsubu => "vwsubu",
            Vwsub => "vwsub",
            VwadduW => "vwaddu.w",
            VwaddW => "vwadd.w",
            VwsubuW => "vwsubu.w",
            VwsubW => "vwsub.w",
            Vwmulu => "vwmulu",
            Vwmulsu => "vwmulsu",
            Vwmul => "vwmul",
            Vwmaccu => "vwmaccu",
            Vwmacc => "vwmacc",
            Vwmaccsu => "vwmaccsu",
            Vwmaccus => "vwmaccus",
            Vnsrl => "vnsrl",
            Vnsra => "vnsra",
            Vnclipu => "vnclipu",
            Vnclip => "vnclip",
            VfcvtXuF => "vfcvt.xu.f.v",
            VfcvtXF => "vfcvt.x.f.v",
            VfcvtFXu => "vfcvt.f.xu.v",
            VfcvtFX => "vfcvt.f.x.v",
            VfcvtRtzXuF => "vfcvt.rtz.xu.f.v",
            VfcvtRtzXF => "vfcvt.rtz.x.f.v",
            VfwcvtXuF => "vfwcvt.xu.f.v",
            VfwcvtXF => "vfwcvt.x.f.v",
            VfwcvtFXu => "vfwcvt.f.xu.v",
            VfwcvtFX => "vfwcvt.f.x.v",
            VfwcvtFF => "vfwcvt.f.f.v",
            VfwcvtRtzXuF => "vfwcvt.rtz.xu.f.v",
            VfwcvtRtzXF => "vfwcvt.rtz.x.f.v",
            VfncvtXuF => "vfncvt.xu.f.w",
            VfncvtXF => "vfncvt.x.f.w",
            VfncvtFXu => "vfncvt.f.xu.w",
            VfncvtFX => "vfncvt.f.x.w",
            VfncvtFF => "vfncvt.f.f.w",
            VfncvtRodFF => "vfncvt.rod.f.f.w",
            VfncvtRtzXuF => "vfncvt.rtz.xu.f.w",
            VfncvtRtzXF => "vfncvt.rtz.x.f.w",
            Vfwadd => "vfwadd",
            Vfwsub => "vfwsub",
            Vfwmul => "vfwmul",
            VfwaddW => "vfwadd.w",
            VfwsubW => "vfwsub.w",
            Vfwmacc => "vfwmacc",
            Vfwnmacc => "vfwnmacc",
            Vfwmsac => "vfwmsac",
            Vfwnmsac => "vfwnmsac",
            Vwredsumu => "vwredsumu",
            Vwredsum => "vwredsum",
            Vfwredusum => "vfwredusum",
            Vfwredosum => "vfwredosum",
            Vfclass => "vfclass.v",
            Vmvr => "vmvr.v",
            Vfrsqrt7 => "vfrsqrt7.v",
            Vfrec7 => "vfrec7.v",
            Illegal => "illegal",
        }
    }

    /// Operand layout class for formatting.
    fn class(self) -> Class {
        use Op::*;
        match self {
            Lui | Auipc => Class::U,
            Jal => Class::J,
            Jalr => Class::Jalr,
            Beq | Bne | Blt | Bge | Bltu | Bgeu => Class::B,
            Lb | Lh | Lw | Lbu | Lhu | Lwu | Ld => Class::Load,
            Sb | Sh | Sw | Sd => Class::Store,
            Flw | Fld | Flh => Class::FLoad,
            Fsw | Fsd | Fsh => Class::FStore,
            Addi | Slti | Sltiu | Xori | Ori | Andi | Addiw => Class::IArith,
            Slli | Srli | Srai | Slliw | Srliw | Sraiw | SlliUw | Rori | Roriw | Bclri | Bexti
            | Binvi | Bseti => Class::Shift,
            Fence => Class::Bare,
            FenceI | Ecall | Ebreak | Mret | Sret | Wfi => Class::Bare,
            Csrrw | Csrrs | Csrrc => Class::Csr,
            Csrrwi | Csrrsi | Csrrci => Class::Csri,
            LrW | LrD => Class::Lr,
            ScW | ScD | AmoswapW | AmoaddW | AmoxorW | AmoandW | AmoorW | AmominW | AmomaxW
            | AmominuW | AmomaxuW | AmoswapD | AmoaddD | AmoxorD | AmoandD | AmoorD | AmominD
            | AmomaxD | AmominuD | AmomaxuD => Class::Amo,
            Clz | Ctz | Cpop | SextB | SextH | ZextH | Clzw | Ctzw | Cpopw | Brev8 | Sha256Sig0
            | Sha256Sig1 | Sha256Sum0 | Sha256Sum1 | Sha512Sig0 | Sha512Sig1 | Sha512Sum0
            | Sha512Sum1 | Sm3p0 | Sm3p1 | Aes64im | Aes64ks1i => Class::Unary,
            FsqrtS | FsqrtD | FroundS | FroundnxS | FroundD | FroundnxD | FsqrtH | FroundH
            | FroundnxH => Class::FUnary,
            FaddS | FsubS | FmulS | FdivS | FsgnjS | FsgnjnS | FsgnjxS | FminS | FmaxS | FaddD
            | FsubD | FmulD | FdivD | FsgnjD | FsgnjnD | FsgnjxD | FminD | FmaxD | FminmS
            | FmaxmS | FminmD | FmaxmD | FaddH | FsubH | FmulH | FdivH | FsgnjH | FsgnjnH
            | FsgnjxH | FminH | FmaxH | FminmH | FmaxmH => Class::FBin,
            FmaddS | FmsubS | FnmsubS | FnmaddS | FmaddD | FmsubD | FnmsubD | FnmaddD | FmaddH
            | FmsubH | FnmsubH | FnmaddH => Class::FMA,
            FeqS | FltS | FleS | FeqD | FltD | FleD | FleqS | FltqS | FleqD | FltqD | FeqH | FltH
            | FleH | FleqH | FltqH => Class::FCmp,
            FliS | FliD | FliH => Class::Fli,
            FcvtWS | FcvtWuS | FcvtLS | FcvtLuS | FmvXW | FclassS | FcvtWD | FcvtWuD | FcvtLD
            | FcvtLuD | FmvXD | FclassD | FcvtmodWD | FcvtWH | FcvtWuH | FcvtLH | FcvtLuH | FmvXH
            | FclassH => Class::FToX,
            FcvtSW | FcvtSWu | FcvtSL | FcvtSLu | FmvWX | FcvtDW | FcvtDWu | FcvtDL | FcvtDLu
            | FmvDX | FcvtHW | FcvtHWu | FcvtHL | FcvtHLu | FmvHX => Class::XToF,
            FcvtSD | FcvtDS | FcvtSH | FcvtHS | FcvtDH | FcvtHD => Class::FToF,
            Vsetvli | Vsetvl => Class::Vset,
            Vsetivli => Class::Vseti,
            Illegal => Class::Bare,
            _ => Class::RArith, // OP / OP-32 / M / Zb register-register
        }
    }
}

enum Class {
    U,
    J,
    Jalr,
    B,
    Load,
    Store,
    FLoad,
    FStore,
    IArith,
    Shift,
    RArith,
    Unary,
    Bare,
    Csr,
    Csri,
    Lr,
    Amo,
    FBin,
    FUnary,
    FMA,
    FCmp,
    FToX,
    XToF,
    FToF,
    Fli,
    Vset,
    Vseti,
}

impl fmt::Display for Insn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let m = self.op.mnemonic();
        let rd = x_name(self.rd);
        let rs1 = x_name(self.rs1);
        let rs2 = x_name(self.rs2);
        let frd = f_name(self.rd);
        let frs1 = f_name(self.rs1);
        let frs2 = f_name(self.rs2);
        let frs3 = f_name(self.rs3);
        let imm = self.imm;
        match self.op.class() {
            Class::U => write!(f, "{m} {rd}, {:#x}", (imm >> 12) & 0xfffff),
            Class::J => write!(f, "{m} {rd}, .{:+#x}", imm),
            Class::Jalr => write!(f, "{m} {rd}, {imm}({rs1})"),
            Class::B => write!(f, "{m} {rs1}, {rs2}, .{:+#x}", imm),
            Class::Load => write!(f, "{m} {rd}, {imm}({rs1})"),
            Class::Store => write!(f, "{m} {rs2}, {imm}({rs1})"),
            Class::FLoad => write!(f, "{m} {frd}, {imm}({rs1})"),
            Class::FStore => write!(f, "{m} {frs2}, {imm}({rs1})"),
            Class::IArith => write!(f, "{m} {rd}, {rs1}, {imm}"),
            Class::Shift => write!(f, "{m} {rd}, {rs1}, {imm}"),
            Class::RArith => write!(f, "{m} {rd}, {rs1}, {rs2}"),
            Class::Unary => write!(f, "{m} {rd}, {rs1}"),
            Class::Bare => write!(f, "{m}"),
            Class::Csr => write!(f, "{m} {rd}, {:#x}, {rs1}", self.csr),
            Class::Csri => write!(f, "{m} {rd}, {:#x}, {}", self.csr, self.rs1),
            Class::Lr => write!(f, "{m} {rd}, ({rs1})"),
            Class::Amo => write!(f, "{m} {rd}, {rs2}, ({rs1})"),
            Class::FBin => write!(f, "{m} {frd}, {frs1}, {frs2}"),
            Class::FUnary => write!(f, "{m} {frd}, {frs1}"),
            Class::FMA => write!(f, "{m} {frd}, {frs1}, {frs2}, {frs3}"),
            Class::FCmp => write!(f, "{m} {rd}, {frs1}, {frs2}"),
            Class::FToX => write!(f, "{m} {rd}, {frs1}"),
            Class::XToF => write!(f, "{m} {frd}, {rs1}"),
            Class::FToF => write!(f, "{m} {frd}, {frs1}"),
            Class::Fli => write!(f, "{m} {frd}, #{}", self.rs1),
            Class::Vset => write!(f, "{m} {rd}, {rs1}, {:#x}", self.imm),
            Class::Vseti => write!(f, "{m} {rd}, {}, {:#x}", self.rs1, self.imm),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::super::decode::decode;
    use super::super::{Isa, Xlen};

    fn dis(w: u32) -> String {
        decode(w, Xlen::Rv64, &Isa::rv64gc()).to_string()
    }

    #[test]
    fn disasm_samples() {
        // addi a0, a1, 5
        assert_eq!(
            dis((5u32 << 20) | (11 << 15) | (10 << 7) | 0x13),
            "addi a0, a1, 5"
        );
        // add a0, a1, a2
        assert_eq!(
            dis((12u32 << 20) | (11 << 15) | (10 << 7) | 0x33),
            "add a0, a1, a2"
        );
        // ld a0, 16(sp)
        assert_eq!(
            dis((16u32 << 20) | (2 << 15) | (3 << 12) | (10 << 7) | 0x03),
            "ld a0, 16(sp)"
        );
        // sd a0, 8(sp)
        assert_eq!(
            dis((0u32 << 25) | (10 << 20) | (2 << 15) | (3 << 12) | (8 << 7) | 0x23),
            "sd a0, 8(sp)"
        );
        // fadd.s fa0, fa1, fa2
        assert_eq!(
            dis((0u32 << 25) | (12 << 20) | (11 << 15) | (10 << 7) | 0x53),
            "fadd.s fa0, fa1, fa2"
        );
        // ecall
        assert_eq!(dis(0x0000_0073), "ecall");
    }
}
