//! AVX-512 specification inventory and generated EVEX byte-coverage checks.
//!
//! This keeps the checked-in AVX-512 spec corpus partitioned at EVEX
//! row/form plus r/m-extension granularity, and verifies generated byte coverage
//! for unimplemented instructions. It does not prove semantic coverage for
//! instructions that the emulator does not implement yet.

#![cfg(feature = "x86_64-suite")]

use std::collections::BTreeSet;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

#[path = "x86_64/avx512_inventory_data.rs"]
mod avx512_inventory_data;

#[path = "x86_64/avx512_spec.rs"]
mod avx512_spec;

use avx512_inventory_data::{
    RAX_EVEX_EXTRA_MNEMONICS_NOT_IN_AVX512_SPEC, RAX_EVEX_SIMD_DIFF_MNEMONICS,
};
use avx512_spec::{
    avx512_spec_evex_rows, evex_asm_modes_for_row, evex_case_variants_for_row, evex_operand_parts,
    evex_rm_operand_index, evex_rm_register_buckets_for_row, raw_evex_spec_bytes_for_variant,
    spec_case_variant_id, spec_row_mode_id, EvexAsmMode, EvexCaseVariant, EvexEncodingKey,
    EvexRmRegisterClass, EvexSpecRow, EvexVl, EvexW,
};

const UNIMPLEMENTED_AVX512: &str = include_str!("x86_64/avx512_unimplemented_mnemonics.txt");
const LLVM_AVX512_SPEC_MATTR: &str = "+avx512f,+avx512bw,+avx512dq,+avx512vl,+avx512fp16,+avx512vnni,+avx512ifma,+avx512vpopcntdq,+avx512vbmi,+avx512vbmi2,+avx512bitalg,+avx512bf16,+avxvnni,+avx512cd,+avx512vp2intersect,+gfni,+vaes,+vpclmulqdq";

#[derive(Clone, Debug)]
struct EvexGeneratedCase {
    source: String,
    cell: String,
    key: EvexEncodingKey,
    variant: EvexCaseVariant,
    asm: String,
    op: Vec<u8>,
}

fn set_from_slice(items: &[&str]) -> BTreeSet<String> {
    items.iter().map(|item| (*item).to_string()).collect()
}

fn set_from_manifest(text: &str) -> BTreeSet<String> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_string)
        .collect()
}

fn assert_sorted_unique(name: &str, items: &[&str]) {
    for window in items.windows(2) {
        assert!(
            window[0] < window[1],
            "{name} must be sorted and unique: {:?}",
            window
        );
    }
}

fn assert_manifest_sorted_unique(name: &str, text: &str) {
    let items = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect::<Vec<_>>();
    for window in items.windows(2) {
        assert!(
            window[0] < window[1],
            "{name} must be sorted and unique: {:?}",
            window
        );
    }
}

fn format_set(set: &BTreeSet<String>) -> String {
    set.iter().cloned().collect::<Vec<_>>().join("\n")
}

fn format_row_set(set: &BTreeSet<String>) -> String {
    set.iter().take(80).cloned().collect::<Vec<_>>().join("\n")
}

fn which(prog: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|dir| dir.join(prog))
        .find(|candidate| candidate.is_file())
}

fn llvm_mc_path() -> Option<PathBuf> {
    std::env::var_os("LLVM_MC")
        .map(PathBuf::from)
        .or_else(|| which("llvm-mc"))
}

fn parse_encoding(text: &str) -> Option<Vec<u8>> {
    let start = text.find("encoding: [")? + "encoding: [".len();
    let rest = &text[start..];
    let end = rest.find(']')?;
    let mut bytes = Vec::new();
    for token in rest[..end].split(',') {
        let token = token.trim().trim_start_matches("0x");
        bytes.push(u8::from_str_radix(token, 16).ok()?);
    }
    Some(bytes)
}

fn assemble_intel_case(llvm_mc: &Path, asm: &str) -> Option<Vec<u8>> {
    let mut child = Command::new(llvm_mc)
        .args([
            "-triple=x86_64",
            "-mcpu=skylake-avx512",
            "-mattr",
            LLVM_AVX512_SPEC_MATTR,
            "-x86-asm-syntax=intel",
            "-show-encoding",
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    child
        .stdin
        .take()
        .unwrap()
        .write_all(format!("{asm}\n").as_bytes())
        .ok()?;

    let output = child.wait_with_output().ok()?;
    if !output.status.success() {
        return None;
    }
    parse_encoding(&String::from_utf8_lossy(&output.stdout))
}

fn strip_operand_decorations(operand: &str) -> (String, bool, bool) {
    let lower = operand.to_ascii_lowercase();
    let has_mask = lower.contains("{k");
    let has_zero = lower.contains("{z}");
    let mut stripped = String::new();
    let mut in_braces = false;

    for ch in operand.chars() {
        match ch {
            '{' => in_braces = true,
            '}' => in_braces = false,
            _ if !in_braces => stripped.push(ch),
            _ => {}
        }
    }

    (
        stripped.split_whitespace().collect::<Vec<_>>().join(" "),
        has_mask,
        has_zero,
    )
}

fn is_vector_register(text: &str) -> bool {
    ["xmm", "ymm", "zmm"].iter().any(|prefix| {
        let Some(rest) = text.strip_prefix(prefix) else {
            return false;
        };
        !rest.is_empty() && rest.chars().all(|ch| ch.is_ascii_digit())
    })
}

fn vector_register_for_operand(text: &str, index: usize) -> Option<String> {
    for prefix in ["xmm", "ymm", "zmm"] {
        if !text.contains(prefix) {
            continue;
        }
        return Some(format!("{prefix}{index}"));
    }
    None
}

fn high_vector_register(text: &str) -> Option<String> {
    for prefix in ["xmm", "ymm", "zmm"] {
        let Some(rest) = text.strip_prefix(prefix) else {
            continue;
        };
        let index = rest.parse::<usize>().ok()?;
        return vector_register_for_operand(text, if index < 16 { index + 16 } else { index });
    }
    None
}

fn mask_operand(mut operand: String, has_mask: bool, has_zero: bool, mode: EvexAsmMode) -> String {
    if has_mask {
        operand.push_str(" {k1}");
    }
    if has_zero && mode == EvexAsmMode::Register {
        operand.push_str(" {z}");
    }
    operand
}

fn gpr_register_for_operand(operand: &str, index: usize) -> Option<String> {
    let lower = operand.to_ascii_lowercase();
    let is_64 = lower.contains("r64") || lower.contains("m64");
    let is_32 = lower == "reg" || lower.contains("r32") || lower.contains("m32");
    let is_16 = lower.contains("r16") || lower.contains("m16");
    let is_8 = lower.contains("r8") || lower.contains("m8");
    match index {
        0 => {
            if is_64 {
                Some("rax".to_string())
            } else if is_32 {
                Some("eax".to_string())
            } else if is_16 {
                Some("ax".to_string())
            } else if is_8 {
                Some("al".to_string())
            } else {
                None
            }
        }
        8 => {
            if is_64 {
                Some("r8".to_string())
            } else if is_32 {
                Some("r8d".to_string())
            } else if is_16 {
                Some("r8w".to_string())
            } else if is_8 {
                Some("r8b".to_string())
            } else {
                None
            }
        }
        _ => None,
    }
}

fn register_for_operand(operand: &str, rm_reg: Option<u8>) -> Option<String> {
    let lower = operand.to_ascii_lowercase();
    let index = rm_reg.unwrap_or(16) as usize;
    if let Some(reg) = vector_register_for_operand(&lower, index) {
        Some(reg)
    } else if let Some(reg) = gpr_register_for_operand(&lower, index) {
        Some(reg)
    } else if lower.contains('k') {
        Some(format!("k{}", index & 7))
    } else {
        None
    }
}

fn first_memory_bits(operand: &str) -> Option<usize> {
    let bytes = operand.as_bytes();
    let mut index = 0;
    while index + 1 < bytes.len() {
        let ch = bytes[index] as char;
        let next = bytes[index + 1] as char;
        let prev_is_alpha = index > 0 && (bytes[index - 1] as char).is_ascii_alphabetic();
        if ch == 'm' && next.is_ascii_digit() && !prev_is_alpha {
            let mut end = index + 1;
            while end < bytes.len() && (bytes[end] as char).is_ascii_digit() {
                end += 1;
            }
            return operand[index + 1..end].parse::<usize>().ok();
        }
        index += 1;
    }
    None
}

fn ptr_name(bits: usize) -> &'static str {
    match bits {
        8 => "byte ptr",
        16 => "word ptr",
        32 => "dword ptr",
        64 => "qword ptr",
        128 => "xmmword ptr",
        256 => "ymmword ptr",
        512 => "zmmword ptr",
        _ => "byte ptr",
    }
}

fn vsib_index_register(operand: &str) -> &'static str {
    if operand.contains("vm32x") || operand.contains("vm64x") {
        "xmm16"
    } else if operand.contains("vm32y") || operand.contains("vm64y") {
        "ymm16"
    } else {
        "zmm16"
    }
}

fn vsib_data_bits(mnemonic: &str) -> usize {
    if mnemonic.ends_with("pd") || mnemonic.ends_with("dq") || mnemonic.ends_with("qq") {
        64
    } else {
        32
    }
}

fn memory_operand_for(operand: &str, mnemonic: &str) -> String {
    let lower = operand.to_ascii_lowercase();
    if lower.contains("vm32") || lower.contains("vm64") {
        let scale = if lower.contains("vm64") { 8 } else { 4 };
        let index = vsib_index_register(&lower);
        return format!(
            "{} [rax + {scale}*{index}]",
            ptr_name(vsib_data_bits(mnemonic))
        );
    }

    let bits = first_memory_bits(&lower).unwrap_or(8);
    format!("{} [rax]", ptr_name(bits))
}

fn substitute_operand(
    operand: &str,
    mode: EvexAsmMode,
    mnemonic: &str,
    rm_reg: Option<u8>,
) -> String {
    let (bare, has_mask, has_zero) = strip_operand_decorations(operand);
    let lower = bare.to_ascii_lowercase();

    if lower.starts_with("imm") || lower == "ib" || lower == "iw" || lower.contains("imm") {
        return "3".to_string();
    }
    if lower.starts_with('k') && lower.contains("+1") {
        return "k2".to_string();
    }
    if lower.starts_with('k')
        && lower[1..]
            .chars()
            .all(|ch| ch.is_ascii_digit() || ch == ' ')
    {
        return lower.replace(' ', "");
    }
    if lower.ends_with("+3")
        && (lower.starts_with("xmm") || lower.starts_with("ymm") || lower.starts_with("zmm"))
    {
        let class = &lower[..3];
        return format!("{class}20");
    }
    if lower == "r32" {
        return gpr_register_for_operand(&lower, rm_reg.unwrap_or(8) as usize)
            .unwrap_or_else(|| "r8d".to_string());
    }
    if lower == "r64" {
        return gpr_register_for_operand(&lower, rm_reg.unwrap_or(8) as usize)
            .unwrap_or_else(|| "r8".to_string());
    }
    if is_vector_register(&lower) {
        let reg = rm_reg
            .and_then(|rm_reg| vector_register_for_operand(&lower, rm_reg as usize))
            .or_else(|| high_vector_register(&lower))
            .unwrap_or(lower);
        return mask_operand(reg, has_mask, has_zero, mode);
    }
    if lower.starts_with('m') && lower.chars().nth(1).is_some_and(|ch| ch.is_ascii_digit()) {
        return mask_operand(memory_operand_for(&lower, mnemonic), has_mask, false, mode);
    }
    if lower.contains("vm32") || lower.contains("vm64") {
        return mask_operand(memory_operand_for(&lower, mnemonic), has_mask, false, mode);
    }
    if lower.contains('/') {
        if mode == EvexAsmMode::Register {
            if let Some(reg) = register_for_operand(&lower, rm_reg) {
                return mask_operand(reg, has_mask, has_zero, mode);
            }
        }
        return mask_operand(memory_operand_for(&lower, mnemonic), has_mask, false, mode);
    }

    mask_operand(lower, has_mask, has_zero, mode)
}

fn generated_case_for_row(row: &EvexSpecRow, variant: EvexCaseVariant) -> EvexGeneratedCase {
    let rm_operand_index = (variant.mode == EvexAsmMode::Register)
        .then(|| evex_rm_operand_index(row))
        .flatten();
    let operands = evex_operand_parts(&row.operands)
        .iter()
        .enumerate()
        .map(|(index, operand)| {
            let rm_reg = (Some(index) == rm_operand_index)
                .then_some(variant.rm_reg)
                .flatten();
            substitute_operand(operand, variant.mode, &row.key.mnemonic, rm_reg)
        })
        .collect::<Vec<_>>()
        .join(", ");
    EvexGeneratedCase {
        source: row.source.clone(),
        cell: row.cell.clone(),
        key: row.key.clone(),
        variant,
        asm: format!("{} {operands}", row.key.mnemonic),
        op: raw_evex_spec_bytes_for_variant(row, variant),
    }
}

fn generated_unimplemented_cases(rows: &[EvexSpecRow]) -> Vec<EvexGeneratedCase> {
    let known_unimplemented = set_from_manifest(UNIMPLEMENTED_AVX512);
    let mut cases = Vec::new();
    for row in rows {
        if !known_unimplemented.contains(&row.key.mnemonic) {
            continue;
        }
        for variant in evex_case_variants_for_row(row) {
            cases.push(generated_case_for_row(row, variant));
        }
    }
    cases
}

fn generated_case_id(case: &EvexGeneratedCase) -> String {
    match case.variant.rm_reg {
        Some(rm_reg) => format!(
            "{} {:?} rm{rm_reg} {}",
            case.source, case.variant.mode, case.cell
        ),
        None => format!("{} {:?} {}", case.source, case.variant.mode, case.cell),
    }
}

fn assert_bytes_match_spec_case(case: &EvexGeneratedCase, bytes: &[u8]) -> Result<(), String> {
    if bytes.len() < 6 || bytes[0] != 0x62 {
        return Err(format!("assembled outside EVEX encoding: {bytes:02x?}"));
    }

    let p0 = bytes[1];
    let p1 = bytes[2];
    let p2 = bytes[3];
    let opcode = bytes[4];
    let modrm = bytes[5];

    if (p0 & 0x7) != case.key.map {
        return Err(format!("EVEX map mismatch: bytes={:#x}", p0 & 0x7));
    }
    if opcode != case.key.opcode {
        return Err(format!("opcode mismatch: bytes={opcode:#x}"));
    }
    if (p1 & 0x3) != case.key.pp {
        return Err(format!("mandatory-prefix mismatch: bytes={:#x}", p1 & 0x3));
    }

    match case.key.w {
        EvexW::W0 if (p1 & 0x80) != 0 => return Err("W mismatch: expected W0".to_string()),
        EvexW::W1 if (p1 & 0x80) == 0 => return Err("W mismatch: expected W1".to_string()),
        _ => {}
    }

    let actual_vl = (p2 >> 5) & 0x3;
    match case.key.vl {
        EvexVl::Vl128 if actual_vl != 0 => return Err("VL mismatch: expected 128".to_string()),
        EvexVl::Vl256 if actual_vl != 1 => return Err("VL mismatch: expected 256".to_string()),
        EvexVl::Vl512 if actual_vl != 2 => return Err("VL mismatch: expected 512".to_string()),
        _ => {}
    }

    if let Some(opcode_ext) = case.key.opcode_ext {
        let actual_ext = (modrm >> 3) & 0x7;
        if actual_ext != opcode_ext {
            return Err(format!("opcode extension mismatch: bytes=/{actual_ext}"));
        }
    }

    let is_register_form = (modrm & 0xc0) == 0xc0;
    match case.variant.mode {
        EvexAsmMode::Register if !is_register_form => {
            return Err("expected ModRM register form".to_string());
        }
        EvexAsmMode::Memory if is_register_form => {
            return Err("expected ModRM memory form".to_string());
        }
        _ => {}
    }

    if let Some(expected_rm_reg) = case.variant.rm_reg {
        let actual_rm_reg = (modrm & 0x7)
            + if (p0 & 0x20) == 0 { 8 } else { 0 }
            + if (p0 & 0x40) == 0 { 16 } else { 0 };
        if actual_rm_reg != expected_rm_reg {
            return Err(format!(
                "EVEX r/m register mismatch: expected {expected_rm_reg}, bytes={actual_rm_reg}"
            ));
        }
    }

    Ok(())
}

fn avx512_spec_mnemonics() -> BTreeSet<String> {
    avx512_spec_evex_rows()
        .into_iter()
        .map(|row| row.key.mnemonic)
        .collect()
}

#[test]
fn avx512_spec_inventory_is_case_variant_partitioned() {
    let rows = avx512_spec_evex_rows();
    assert!(!rows.is_empty(), "AVX-512 EVEX spec row inventory is empty");

    let implemented = set_from_slice(RAX_EVEX_SIMD_DIFF_MNEMONICS);
    let known_unimplemented = set_from_manifest(UNIMPLEMENTED_AVX512);
    let spec = avx512_spec_mnemonics();
    let known_unimplemented_evex = known_unimplemented
        .intersection(&spec)
        .cloned()
        .collect::<BTreeSet<_>>();

    let mut implemented_case_variants = BTreeSet::new();
    let mut unimplemented_case_variants = BTreeSet::new();
    let mut unclassified_case_variants = BTreeSet::new();
    let mut unknown_register_rm_operands = BTreeSet::new();

    for row in &rows {
        if evex_asm_modes_for_row(row).contains(&EvexAsmMode::Register)
            && avx512_spec::evex_rm_register_class(row) == EvexRmRegisterClass::Unknown
        {
            unknown_register_rm_operands.insert(spec_row_mode_id(row, EvexAsmMode::Register));
        }

        for variant in evex_case_variants_for_row(row) {
            let row_key = format!("{:?} {}", row.key, spec_case_variant_id(row, variant));
            if implemented.contains(&row.key.mnemonic) {
                implemented_case_variants.insert(row_key);
            } else if known_unimplemented.contains(&row.key.mnemonic) {
                unimplemented_case_variants.insert(row_key);
            } else {
                unclassified_case_variants.insert(row_key);
            }
        }
    }

    assert!(
        unclassified_case_variants.is_empty(),
        "AVX-512 EVEX case variants must be classified as differential-covered or unimplemented:\n{}",
        format_row_set(&unclassified_case_variants)
    );
    assert!(
        unknown_register_rm_operands.is_empty(),
        "AVX-512 EVEX register forms must have a known r/m operand class:\n{}",
        format_row_set(&unknown_register_rm_operands)
    );
    assert!(
        !implemented_case_variants.is_empty(),
        "no implemented AVX-512 EVEX case variants were classified"
    );
    assert!(
        implemented_case_variants.len()
            > implemented.intersection(&avx512_spec_mnemonics()).count(),
        "implemented AVX-512 EVEX coverage must be case-variant-level, not mnemonic-only"
    );
    if !known_unimplemented_evex.is_empty() {
        assert!(
            unimplemented_case_variants.len() > known_unimplemented_evex.len(),
            "unimplemented AVX-512 EVEX coverage must be case-variant-level, not mnemonic-only"
        );
    }
}

#[test]
fn avx512_unimplemented_evex_case_variants_have_generated_byte_coverage() {
    let llvm_mc = llvm_mc_path();
    if llvm_mc.is_none() {
        eprintln!("[info] llvm-mc unavailable; using raw EVEX spec bytes");
    }

    let rows = avx512_spec_evex_rows();
    let known_unimplemented = set_from_manifest(UNIMPLEMENTED_AVX512);
    let expected_case_variants = rows
        .iter()
        .filter(|row| known_unimplemented.contains(&row.key.mnemonic))
        .flat_map(|row| {
            evex_case_variants_for_row(row)
                .into_iter()
                .map(|variant| spec_case_variant_id(row, variant))
        })
        .collect::<BTreeSet<_>>();
    let cases = generated_unimplemented_cases(&rows);

    if expected_case_variants.is_empty() {
        assert!(
            cases.is_empty(),
            "unimplemented AVX-512 EVEX byte corpus must be empty when the manifest is empty"
        );
        return;
    }
    assert!(
        cases.len() >= expected_case_variants.len(),
        "unimplemented EVEX byte coverage must include split register/memory and r/m-extension forms"
    );

    for row in rows
        .iter()
        .filter(|row| known_unimplemented.contains(&row.key.mnemonic))
    {
        if !evex_asm_modes_for_row(row).contains(&EvexAsmMode::Register) {
            continue;
        }

        let actual_rm_regs = cases
            .iter()
            .filter(|case| {
                case.source == row.source
                    && case.cell == row.cell
                    && case.variant.mode == EvexAsmMode::Register
            })
            .filter_map(|case| case.variant.rm_reg)
            .collect::<BTreeSet<_>>();
        let expected_rm_regs = evex_rm_register_buckets_for_row(row)
            .into_iter()
            .collect::<BTreeSet<_>>();
        assert_eq!(
            actual_rm_regs,
            expected_rm_regs,
            "{} must cover every valid EVEX r/m register bucket for its operand class",
            spec_row_mode_id(row, EvexAsmMode::Register)
        );

        if avx512_spec::evex_rm_register_class(row) == EvexRmRegisterClass::Vector {
            assert_eq!(
                actual_rm_regs,
                BTreeSet::from([0, 8, 16, 24]),
                "{} must cover all vector EVEX.X/B r/m extension buckets",
                spec_row_mode_id(row, EvexAsmMode::Register)
            );
        }
    }

    let mut failures = Vec::new();
    let mut covered_case_variants = BTreeSet::new();

    for case in &cases {
        let llvm_bytes = llvm_mc
            .as_deref()
            .and_then(|llvm_mc| assemble_intel_case(llvm_mc, &case.asm));
        let bytes = match llvm_bytes {
            Some(bytes) if assert_bytes_match_spec_case(case, &bytes).is_ok() => bytes,
            _ => case.op.clone(),
        };

        if let Err(error) = assert_bytes_match_spec_case(case, &bytes) {
            failures.push(format!(
                "{}: {error}\n  spec: {}\n  asm: {}\n  bytes: {:02x?}",
                generated_case_id(case),
                case.cell,
                case.asm,
                bytes
            ));
            continue;
        }

        covered_case_variants.insert(generated_case_id(case));
    }

    let missing_case_variants = expected_case_variants
        .difference(&covered_case_variants)
        .cloned()
        .collect::<BTreeSet<_>>();

    assert!(
        failures.is_empty() && missing_case_variants.is_empty(),
        "unimplemented AVX-512 EVEX byte coverage mismatch\nfailures:\n{}\nmissing case variants:\n{}",
        failures.into_iter().take(80).collect::<Vec<_>>().join("\n"),
        format_row_set(&missing_case_variants)
    );
}

#[test]
fn avx512_spec_inventory_is_partitioned() {
    assert_sorted_unique("RAX_EVEX_SIMD_DIFF_MNEMONICS", RAX_EVEX_SIMD_DIFF_MNEMONICS);
    assert_sorted_unique(
        "RAX_EVEX_EXTRA_MNEMONICS_NOT_IN_AVX512_SPEC",
        RAX_EVEX_EXTRA_MNEMONICS_NOT_IN_AVX512_SPEC,
    );
    assert_manifest_sorted_unique("avx512_unimplemented_mnemonics.txt", UNIMPLEMENTED_AVX512);

    let spec = avx512_spec_mnemonics();
    let implemented = set_from_slice(RAX_EVEX_SIMD_DIFF_MNEMONICS);
    let implemented_extra = set_from_slice(RAX_EVEX_EXTRA_MNEMONICS_NOT_IN_AVX512_SPEC);
    let known_unimplemented = set_from_manifest(UNIMPLEMENTED_AVX512);
    let known_unimplemented_evex = known_unimplemented
        .intersection(&spec)
        .cloned()
        .collect::<BTreeSet<_>>();

    let actual_extra = implemented
        .difference(&spec)
        .cloned()
        .collect::<BTreeSet<_>>();
    assert_eq!(
        actual_extra, implemented_extra,
        "rax-supported EVEX mnemonics outside the AVX-512 spec corpus changed"
    );

    let overlap = implemented
        .intersection(&known_unimplemented_evex)
        .cloned()
        .collect::<BTreeSet<_>>();
    assert!(
        overlap.is_empty(),
        "mnemonics cannot be both implemented and known-unimplemented:\n{}",
        format_set(&overlap)
    );

    let unimplemented_not_in_spec = known_unimplemented_evex
        .difference(&spec)
        .cloned()
        .collect::<BTreeSet<_>>();
    assert!(
        unimplemented_not_in_spec.is_empty(),
        "known-unimplemented manifest contains mnemonics not in the AVX-512 spec corpus:\n{}",
        format_set(&unimplemented_not_in_spec)
    );

    let mut partition = known_unimplemented_evex.clone();
    partition.extend(implemented.intersection(&spec).cloned());

    let missing = spec
        .difference(&partition)
        .cloned()
        .collect::<BTreeSet<_>>();
    let unexpected = partition
        .difference(&spec)
        .cloned()
        .collect::<BTreeSet<_>>();

    assert!(
        missing.is_empty() && unexpected.is_empty(),
        "AVX-512 spec inventory mismatch\nmissing from implemented-or-unimplemented partition:\n{}\nunexpected in partition:\n{}",
        format_set(&missing),
        format_set(&unexpected)
    );
}
