#!/usr/bin/env python3
"""Generate the *control-flow* Hexagon differential oracle (oracle_cf.s).

The reg-only oracle (gen_oracle.py) patches a single (always-legal, never
branching) test packet into a 4-word slot whose fall-through is the capture
epilogue. That cannot test control flow: a taken branch or a hardware-loop
back-edge escapes the epilogue, and the loop body must actually re-execute for
its register/loop-state effects to be observable.

This oracle makes control flow observable by running a *whole assembled code
fragment* (prologue-free; the harness assembles it with `llvm-mc -filetype=obj`
so all PC-relative branch/loop offsets are already relocated) inside a large,
NOP-padded executable region. Layout per case:

    [load architectural state]
    testslot:                      <- N program words copied here; rest NOP
        <fragment: loop setup / branches / body / endloop / ...>
        <trailing NOPs ...>        <- any fall-through path lands here
    { jump epilogue }              <- fixed: every fall-through reaches the pad
    epilogue:                      <- capture full register file (incl. LC/SA/USR)

Because the fragment is self-contained (loop back-edges target labels *inside*
itself, conditional jumps reconverge *inside* itself), it can branch and loop
freely; whatever path it takes, it eventually falls off the end into the NOP
pad and is funnelled to the capture epilogue. The captured state therefore
reflects how many loop iterations ran and which branch path executed (made
observable by writing distinct sentinel registers on each path before
reconverging).

The wire is identical to gen_oracle.py except the per-case word array is
`NMAX_WORDS` long instead of 4 (a fragment is several packets).

Protocol (little-endian binary, stdin -> stdout):
  InCase  = u32 nwords; u32 words[NMAX_WORDS]; HexState st
  OutCase = HexState st; u32 trapped; u32 valid

HexState is the same 176-byte, 44-u32 layout as gen_oracle.py (r0..r31, pred,
usr, m0, m1, gp, cs0, cs1, sa0, lc0, sa1, lc1, pc).
"""

import sys

NOP = 0x7F00C000
# Up to this many program words per case (a control-flow fragment spans several
# packets). The Rust harness sends exactly this many words (NOP-padded).
NMAX_WORDS = 32

# HexState field byte offsets (identical to gen_oracle.py).
O_R = 0
O_PRED = 128
O_USR = 132
O_M0 = 136
O_M1 = 140
O_GP = 144
O_CS0 = 148
O_CS1 = 152
O_SA0 = 156
O_LC0 = 160
O_SA1 = 164
O_LC1 = 168
ST_SIZE = 176

# (control-register number, state offset). Restored before the GPRs; r0 is the
# scratch and is loaded last.
CREGS = [
    (8, O_USR),
    (6, O_M0),
    (7, O_M1),
    (11, O_GP),
    (12, O_CS0),
    (13, O_CS1),
    (0, O_SA0),
    (1, O_LC0),
    (2, O_SA1),
    (3, O_LC1),
    (4, O_PRED),
]

# InCase layout.
CASE_NWORDS = 0
CASE_WORDS = 4
CASE_ST = CASE_WORDS + NMAX_WORDS * 4  # after the word array
CASE_SIZE = CASE_ST + ST_SIZE
# OutCase layout.
OUT_ST = 0
OUT_TRAPPED = ST_SIZE
OUT_VALID = ST_SIZE + 4
OUT_SIZE = ST_SIZE + 8

# Test region: must hold the largest fragment plus a NOP landing pad so any
# fall-through path reaches the trailing `{ jump epilogue }`.
SLOT_WORDS = NMAX_WORDS + 8


def emit(out):
    p = lambda s="": out.append(s)

    p("// AUTO-GENERATED by tools/hexagon-diff/gen_oracle_cf.py -- do not edit.")
    p("// Control-flow / hardware-loop Hexagon differential oracle (qemu-hexagon).")
    p(".text")
    p(".globl _start")
    p("_start:")
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call write_exact }")
    p("\t{ r0 = memw(##g_hdr+4) }")
    p("\t{ memw(##g_rem) = r0 }")
    p(".loop:")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ p0 = cmp.eq(r0,#0); if (p0.new) jump:nt .done }")
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_case }")
    p(f"\t{{ r2 = #{CASE_SIZE} }}")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ call run_case }")
    p("\t{ r0 = #0 }")
    p(f"\t{{ memw(##g_out+{OUT_TRAPPED}) = r0 }}")
    p("\t{ r0 = #1 }")
    p(f"\t{{ memw(##g_out+{OUT_VALID}) = r0 }}")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_out }")
    p(f"\t{{ r2 = #{OUT_SIZE} }}")
    p("\t{ call write_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ r0 = add(r0,#-1) }")
    p("\t{ memw(##g_rem) = r0 }")
    p("\t{ jump .loop }")
    p(".done:")
    p("\t{ r0 = #0 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p(".fail:")
    p("\t{ r0 = #1 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p("")

    for (name, sysnr) in (("read_exact", 63), ("write_exact", 64)):
        tag = name[:2]  # 're' / 'wr'
        p(f"{name}:")
        p("\t{ r16 = r0; r17 = r1; r18 = r2 }")
        p(f".{tag}_loop:")
        p(f"\t{{ p0 = cmp.eq(r18,#0); if (p0.new) jump:nt .{tag}_ok }}")
        p("\t{ r0 = r16; r1 = r17; r2 = r18 }")
        p(f"\t{{ r6 = #{sysnr} }}")
        p("\t{ trap0(#1) }")
        p(f"\t{{ p0 = cmp.gt(r0,#0); if (!p0.new) jump:nt .{tag}_err }}")
        p("\t{ r17 = add(r17,r0) }")
        p("\t{ r18 = sub(r18,r0) }")
        p(f"\t{{ jump .{tag}_loop }}")
        p(f".{tag}_ok:")
        p("\t{ r0 = #0 }")
        p("\t{ jumpr r31 }")
        p(f".{tag}_err:")
        p("\t{ r0 = #-1 }")
        p("\t{ jumpr r31 }")
        p("")

    # ----- run_case -----
    p("run_case:")
    # Save all harness GPRs (r31 = caller return).
    for i in range(32):
        p(f"\t{{ memw(##g_hsave+{i*4}) = r{i} }}")
    # NOP-fill the whole slot, then copy the N program words to the front. The
    # slot is filled first so any fall-through past the program lands in NOPs and
    # is funnelled to the trailing `{ jump epilogue }`.
    p(f"\t{{ r4 = ##{NOP:#x} }}")
    for w in range(SLOT_WORDS):
        p(f"\t{{ memw(##testslot+{w*4}) = r4 }}")
    p(f"\t{{ r5 = memw(##g_case+{CASE_NWORDS}) }}")   # nwords
    for w in range(NMAX_WORDS):
        p(f"\t{{ p0 = cmp.gt(r5,#{w}) }}")
        p(f"\t{{ r3 = memw(##g_case+{CASE_WORDS + w*4}) }}")
        p(f"\t{{ if (p0) memw(##testslot+{w*4}) = r3 }}")
    p("\t{ isync }")
    # Install control registers (r0 = scratch). SA0/SA1/LC0/LC1 come from the
    # input state too, but the test fragment normally overwrites them via its
    # own loop-setup packet.
    for creg, off in CREGS:
        p(f"\t{{ r0 = memw(##g_case+{CASE_ST + off}) }}")
        p(f"\t{{ c{creg} = r0 }}")
    # Load r1..r31 then r0 (r0 last so the scratch use above is overwritten).
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_case+{CASE_ST + O_R + i*4}) }}")
    # ---- test fragment executes here; any fall-through reaches the jump ----
    p("testslot:")
    p(f"\t.space {SLOT_WORDS * 4}")
    p("\t{ jump epilogue }")
    # ---- capture ----
    p("epilogue:")
    for i in range(32):
        p(f"\t{{ memw(##g_out+{OUT_ST + O_R + i*4}) = r{i} }}")
    for creg, off in CREGS:
        p(f"\t{{ r0 = c{creg} }}")
        p(f"\t{{ memw(##g_out+{OUT_ST + off}) = r0 }}")
    # Restore harness GPRs (r0 last) and return.
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_hsave+{i*4}) }}")
    p("\t{ jumpr r31 }")
    p("")

    # ----- data -----
    p(".bss")
    p(".p2align 4")
    p("g_hdr:   .space 8")
    p("g_rem:   .space 4")
    p(".p2align 4")
    p(f"g_case:  .space {CASE_SIZE}")
    p(".p2align 4")
    p(f"g_out:   .space {OUT_SIZE}")
    p(".p2align 4")
    p("g_hsave: .space 128")
    p("")


def main():
    out = []
    emit(out)
    text = "\n".join(out) + "\n"
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as f:
            f.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
