#!/usr/bin/env python3
"""HVX load/store differential oracle (oracle_hvx_mem.s).

Extends the HVX vector oracle with a 128-byte-aligned memory ARENA that `vmem`
loads/stores can target. Per case the input arena is copied into the aligned
`g_varena`, the test packet runs (with a GPR pointing at `g_varena`), and the
arena + vector register file are captured back. Assemble with `llvm-mc -mhvx`.

Wire (little-endian): InCase = nwords(4); words[4](16); HexState(176); pad->256;
vregs[32*128]; arena[ARENA].  OutCase = HexState(176); trapped(4); valid(4);
pad->256; vregs[32*128]; arena[ARENA].
"""

import sys

NOP = 0x7F00C000
VREGS = 32
VBYTES = 128
ARENA = 512  # 4 vectors

O_R = 0
O_PRED = 128
O_USR = 132
O_M0 = 136
O_M1 = 140
O_GP = 144
O_CS0 = 148
O_CS1 = 152
O_SA0 = 156
O_LC0 = 160
O_SA1 = 164
O_LC1 = 168
ST_SIZE = 176

CREGS = [
    (8, O_USR), (6, O_M0), (7, O_M1), (11, O_GP), (12, O_CS0), (13, O_CS1),
    (0, O_SA0), (1, O_LC0), (2, O_SA1), (3, O_LC1), (4, O_PRED),
]

CASE_NWORDS = 0
CASE_WORDS = 4
CASE_ST = 20
CASE_VREGS = 256
CASE_ARENA = CASE_VREGS + VREGS * VBYTES  # 4352
CASE_SIZE = CASE_ARENA + ARENA
OUT_ST = 0
OUT_TRAPPED = ST_SIZE
OUT_VALID = ST_SIZE + 4
OUT_VREGS = 256
OUT_ARENA = OUT_VREGS + VREGS * VBYTES
OUT_SIZE = OUT_ARENA + ARENA


def emit(out):
    p = lambda s="": out.append(s)
    p("// AUTO-GENERATED by tools/hexagon-diff/gen_oracle_hvx_mem.py -- do not edit.")
    p("// HVX load/store differential oracle (runs under qemu-hexagon).")
    p(".text")
    p(".globl _start")
    p("_start:")
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call write_exact }")
    p("\t{ r0 = memw(##g_hdr+4) }")
    p("\t{ memw(##g_rem) = r0 }")
    p(".loop:")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ p0 = cmp.eq(r0,#0); if (p0.new) jump:nt .done }")
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_case }")
    p(f"\t{{ r2 = #{CASE_SIZE} }}")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ call run_case }")
    p("\t{ r0 = #0 }")
    p(f"\t{{ memw(##g_out+{OUT_TRAPPED}) = r0 }}")
    p("\t{ r0 = #1 }")
    p(f"\t{{ memw(##g_out+{OUT_VALID}) = r0 }}")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_out }")
    p(f"\t{{ r2 = #{OUT_SIZE} }}")
    p("\t{ call write_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ r0 = add(r0,#-1) }")
    p("\t{ memw(##g_rem) = r0 }")
    p("\t{ jump .loop }")
    p(".done:")
    p("\t{ r0 = #0 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p(".fail:")
    p("\t{ r0 = #1 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p("")
    for (name, sysnr) in (("read_exact", 63), ("write_exact", 64)):
        tag = name[:2]
        p(f"{name}:")
        p("\t{ r16 = r0; r17 = r1; r18 = r2 }")
        p(f".{tag}_loop:")
        p(f"\t{{ p0 = cmp.eq(r18,#0); if (p0.new) jump:nt .{tag}_ok }}")
        p("\t{ r0 = r16; r1 = r17; r2 = r18 }")
        p(f"\t{{ r6 = #{sysnr} }}")
        p("\t{ trap0(#1) }")
        p(f"\t{{ p0 = cmp.gt(r0,#0); if (!p0.new) jump:nt .{tag}_err }}")
        p("\t{ r17 = add(r17,r0) }")
        p("\t{ r18 = sub(r18,r0) }")
        p(f"\t{{ jump .{tag}_loop }}")
        p(f".{tag}_ok:")
        p("\t{ r0 = #0 }")
        p("\t{ jumpr r31 }")
        p(f".{tag}_err:")
        p("\t{ r0 = #-1 }")
        p("\t{ jumpr r31 }")
        p("")

    def copy_loop(label, src_expr, dst_expr, size):
        p(f"\t{{ r0 = {src_expr} }}")
        p(f"\t{{ r1 = {dst_expr} }}")
        p(f"\t{{ r2 = #{size} }}")
        p(f".{label}:")
        p(f"\t{{ p0 = cmp.eq(r2,#0); if (p0.new) jump:nt .{label}_done }}")
        p("\t{ r3 = memw(r0+#0) }")
        p("\t{ memw(r1+#0) = r3 }")
        p("\t{ r0 = add(r0,#4) }")
        p("\t{ r1 = add(r1,#4) }")
        p("\t{ r2 = add(r2,#-4) }")
        p(f"\t{{ jump .{label} }}")
        p(f".{label}_done:")

    p("run_case:")
    for i in range(32):
        p(f"\t{{ memw(##g_hsave+{i*4}) = r{i} }}")
    copy_loop("ain", f"##g_case+{CASE_ARENA}", "##g_varena", ARENA)
    # copy test words into the slot; NOP-fill.
    p(f"\t{{ r5 = memw(##g_case+{CASE_NWORDS}) }}")
    p(f"\t{{ r4 = ##{NOP:#x} }}")
    for w in range(4):
        p(f"\t{{ p0 = cmp.gt(r5,#{w}) }}")
        p(f"\t{{ r3 = memw(##g_case+{CASE_WORDS + w*4}) }}")
        p("\t{ if (!p0) r3 = r4 }")
        p(f"\t{{ memw(##testslot+{w*4}) = r3 }}")
    p("\t{ isync }")
    # load V0..V31 (post-increment, vmem #s4 range is -8..7).
    p(f"\t{{ r0 = ##g_case+{CASE_VREGS} }}")
    for i in range(VREGS):
        p(f"\t{{ v{i} = vmem(r0++#1) }}")
    for creg, off in CREGS:
        p(f"\t{{ r0 = memw(##g_case+{CASE_ST + off}) }}")
        p(f"\t{{ c{creg} = r0 }}")
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_case+{CASE_ST + O_R + i*4}) }}")
    p("testslot:")
    p("\t.space 16")
    p("epilogue:")
    for i in range(32):
        p(f"\t{{ memw(##g_out+{OUT_ST + O_R + i*4}) = r{i} }}")
    for creg, off in CREGS:
        p(f"\t{{ r0 = c{creg} }}")
        p(f"\t{{ memw(##g_out+{OUT_ST + off}) = r0 }}")
    p(f"\t{{ r0 = ##g_out+{OUT_VREGS} }}")
    for i in range(VREGS):
        p(f"\t{{ vmem(r0++#1) = v{i} }}")
    copy_loop("aout", "##g_varena", f"##g_out+{OUT_ARENA}", ARENA)
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_hsave+{i*4}) }}")
    p("\t{ jumpr r31 }")
    p("")

    p(".bss")
    p(".p2align 4")
    p("g_hdr:   .space 8")
    p("g_rem:   .space 4")
    p(".p2align 7")
    p(f"g_case:  .space {CASE_SIZE}")
    p(".p2align 7")
    p(f"g_out:   .space {OUT_SIZE}")
    p(".p2align 4")
    p("g_hsave: .space 128")
    p(".p2align 7")
    p(".globl g_varena")
    p(f"g_varena: .space {ARENA}")
    p("")


def main():
    out = []
    emit(out)
    text = "\n".join(out) + "\n"
    if len(sys.argv) > 1:
        open(sys.argv[1], "w").write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
